# Generated by Django 5.2.13 on 2026-04-09 08:24

import django.db.models.deletion
import taller.models
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('telefono', models.CharField(max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Configuracion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_taller', models.CharField(default='Taller Juárez', max_length=150)),
                ('porcentaje_iva_actual', models.DecimalField(decimal_places=2, default=Decimal('0.16'), help_text='Ejemplo: 0.16 para 16%, 0.21 para 21%', max_digits=4)),
            ],
            options={
                'verbose_name': 'Configuración',
                'verbose_name_plural': 'Configuraciones',
            },
        ),
        migrations.CreateModel(
            name='Mecanico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Refaccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('stock', models.PositiveIntegerField(default=0)),
                ('precio_neto', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Auto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placa', models.CharField(db_index=True, max_length=15, unique=True)),
                ('marca', models.CharField(max_length=50)),
                ('modelo', models.CharField(max_length=50)),
                ('anio', models.PositiveSmallIntegerField(verbose_name='Año')),
                ('color', models.CharField(max_length=30)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='autos', to='taller.cliente')),
            ],
        ),
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_agenda', models.DateField(db_index=True)),
                ('hora_agenda', models.TimeField()),
                ('km_entrada', models.PositiveIntegerField()),
                ('estado', models.CharField(choices=[('Pendiente', 'Pendiente'), ('En Proceso', 'En Proceso'), ('Entregado', 'Entregado')], db_index=True, default='Pendiente', max_length=20)),
                ('costo_mano_obra_neto', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('costo_refacciones_neto', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=10)),
                ('subtotal_neto', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=10)),
                ('porcentaje_iva_aplicado', models.DecimalField(decimal_places=2, default=taller.models.obtener_iva_vigente, max_digits=4)),
                ('iva_total', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=10)),
                ('gran_total', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=10)),
                ('creado_el', models.DateTimeField(auto_now_add=True)),
                ('auto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='servicios', to='taller.auto')),
                ('mecanico', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='servicios', to='taller.mecanico')),
            ],
        ),
        migrations.CreateModel(
            name='DetalleRefaccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveSmallIntegerField()),
                ('precio_unitario_neto', models.DecimalField(decimal_places=2, help_text='Precio al momento', max_digits=10)),
                ('refaccion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='taller.refaccion')),
                ('servicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='refacciones_usadas', to='taller.servicio')),
            ],
        ),
    ]
