# Generated by Django 5.2.13 on 2026-04-09 17:50

import taller.models
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taller', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configuracion',
            name='porcentaje_iva_actual',
            field=models.DecimalField(decimal_places=2, default=Decimal('16.00'), help_text='Porcentaje de IVA (Ejemplo: 16 para 16%, 21 para 21%)', max_digits=5),
        ),
        migrations.AlterField(
            model_name='servicio',
            name='porcentaje_iva_aplicado',
            field=models.DecimalField(decimal_places=2, default=taller.models.obtener_iva_vigente, max_digits=5),
        ),
    ]
