# Generated by Django 5.2.13 on 2026-04-10 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taller', '0002_alter_configuracion_porcentaje_iva_actual_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicio',
            name='estado',
            field=models.CharField(choices=[('Pendiente', 'Pendiente'), ('En Proceso', 'En Proceso'), ('Terminado', 'Terminado'), ('Entregado', 'Entregado')], db_index=True, default='Pendiente', max_length=20),
        ),
    ]
